name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libgconf-2-4 libfontconfig1

      - name: Install Dependencies
        run: npm install

      - name: Run Selenium Tests
        run: npm test
